# Generated by Django 5.2.9 on 2026-01-09 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregiver_portal', '0001_initial'),
        ('clients', '0009_remove_visit_caregiver_remove_visit_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='clients.invoice'),
        ),
    ]
