# Generated by Django 5.2.9 on 2026-01-10 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregiver_portal', '0002_visit_invoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='bill_rate',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='caregiver_name',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='clock_in',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='clock_out',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='duration_hours',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='pay_rate',
        ),
        migrations.AddField(
            model_name='visit',
            name='caregiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visit',
            name='end_time',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='start_time',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
