# Generated by Django 5.2.9 on 2026-01-15 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregiver_portal', '0003_remove_visit_bill_rate_remove_visit_caregiver_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='start_time',
        ),
        migrations.AddField(
            model_name='visit',
            name='clock_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='clock_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='duration_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='mileage',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Total miles driven for this visit', max_digits=6, null=True),
        ),
        migrations.CreateModel(
            name='VisitComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='caregiver_portal.visit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
