# Generated by Django 5.2.9 on 2026-01-15 20:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregiver_portal', '0004_remove_visit_end_time_remove_visit_start_time_and_more'),
        ('clients', '0012_client_active_client_adls_client_care_needs_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['caregiver', 'clock_in'], name='idx_visit_cg_clockin'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['clock_out'], name='idx_visit_clockout'),
        ),
    ]
