# Generated by Django 5.2.9 on 2026-01-15 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregiver_portal', '0005_add_dashboard_indexes'),
        ('shifts', '0004_add_dashboard_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='shift',
            field=models.ForeignKey(blank=True, help_text='Linked shift if this is a scheduled visit, null for unscheduled visits', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='shifts.shift'),
        ),
    ]
