# Generated by Django 5.2.9 on 2026-01-15 20:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregiver_portal', '0006_add_shift_fk_and_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='mileage',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Total miles driven for this visit (max 500)', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0, message='Mileage cannot be negative.'), django.core.validators.MaxValueValidator(500, message='Mileage cannot exceed 500 miles per visit.')]),
        ),
    ]
