# Generated by Django 5.2.9 on 2026-01-15 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregiver_portal', '0007_add_mileage_validation'),
        ('shifts', '0004_add_dashboard_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('clock_in', 'Clock In'), ('clock_out', 'Clock Out'), ('visit_create', 'Visit Created'), ('visit_update', 'Visit Updated'), ('visit_delete', 'Visit Deleted'), ('mileage_update', 'Mileage Updated'), ('login', 'User Login'), ('logout', 'User Logout'), ('permission_denied', 'Permission Denied')], db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shifts.shift')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='caregiver_portal.visit')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='caregiver_p_user_id_a04b82_idx'), models.Index(fields=['action', 'timestamp'], name='caregiver_p_action_e7d285_idx'), models.Index(fields=['visit'], name='caregiver_p_visit_i_7cc2e9_idx')],
            },
        ),
    ]
