# Generated by Django 5.2.9 on 2026-01-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregiver_portal', '0008_add_audit_log_and_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='clock_in_accuracy',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GPS accuracy in meters at clock-in', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='clock_in_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude where caregiver clocked in', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='clock_in_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude where caregiver clocked in', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='clock_out_accuracy',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GPS accuracy in meters at clock-out', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='clock_out_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude where caregiver clocked out', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='clock_out_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude where caregiver clocked out', max_digits=9, null=True),
        ),
    ]
