# Generated by Django 5.2.9 on 2026-01-16 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregiver_portal', '0009_add_geolocation_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClockEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('clock_in', 'Clock In'), ('clock_out', 'Clock Out'), ('auto_clock_out', 'System Auto Clock-Out'), ('manual_correction', 'Manual Correction')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recorded_time', models.DateTimeField(help_text='The actual time recorded')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_disputed', models.BooleanField(default=False)),
                ('dispute_reason', models.TextField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_clock_events', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clock_events', to='caregiver_portal.visit')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['visit', 'event_type'], name='caregiver_p_visit_i_f4b274_idx')],
            },
        ),
    ]
