# Generated by Django 5.2.9 on 2026-01-16 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregiver_portal', '0010_add_clockevent_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='The Monday that starts the week')),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_visits', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start', 'caregiver'],
                'indexes': [models.Index(fields=['week_start', 'caregiver'], name='caregiver_p_week_st_8b7802_idx')],
                'unique_together': {('caregiver', 'week_start')},
            },
        ),
    ]
