# Generated by Django 5.2.9 on 2026-01-10 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0010_client_address_line1_client_city_client_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_needs', models.TextField(blank=True, null=True)),
                ('demographics', models.TextField(blank=True, null=True)),
                ('community_care', models.TextField(blank=True, null=True)),
                ('adls', models.TextField(blank=True, null=True)),
                ('iadls', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='care_assessment', to='clients.client')),
            ],
        ),
    ]
