# Generated by Django 5.2.9 on 2026-01-09 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []
        
    
    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in', models.DateTimeField(blank=True, null=True)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('in_lat', models.FloatField(blank=True, null=True)),
                ('in_lng', models.FloatField(blank=True, null=True)),
                ('out_lat', models.FloatField(blank=True, null=True)),
                ('out_lng', models.FloatField(blank=True, null=True)),
                ('accuracy_m', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeclock_entries', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clock_entries', to='shifts.shift')),
            ],
        ),
    ]
