# Generated by Django 5.2.9 on 2026-01-09 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_type', models.CharField(choices=[('CPR', 'CPR Certification'), ('TB', 'TB Test'), ('ID', 'Government ID'), ('LICENSE', 'Professional License'), ('BACKGROUND', 'Background Check'), ('OTHER', 'Other')], max_length=20)),
                ('document', models.FileField(blank=True, null=True, upload_to='employee_credentials/')),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_credentials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
