# Generated by Django 5.2.9 on 2026-01-03 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_client_active_remove_client_care_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='shift',
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='radius_meters',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, default='')),
                ('care_plan', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='clients.client')),
            ],
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
