# Generated by Django 5.2.9 on 2026-01-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='duration_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
