# Generated by Django 5.2.9 on 2026-01-11 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_client_address_line1_client_city_client_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='client',
            name='city',
        ),
        migrations.RemoveField(
            model_name='client',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='client',
            name='state',
        ),
        migrations.RemoveField(
            model_name='client',
            name='zip_code',
        ),
    ]
