# Generated by Django 5.2.9 on 2026-01-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_add_event_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='client_photos/'),
        ),
    ]
