# Generated by Django 5.2.9 on 2026-01-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
